languageCode = "zh-CN"
languageName = "Chinese"
weight = 1

title = "æ§¿å‘ˆGoidea"
#copyright = "Copy, _right?_ :thinking_face:"

[params]
  isoCode = "zh-cn"
  displayName = "CN"
  rtl = false

  dateFormat = "January 2, 2006"

  mainSections = ["posts","newsletter"]
  description = "è¯»ä¹¦ï½œæ–°çŸ¥ï½œç”Ÿæ´»ç¦…"

[author]
  name = "L,.G."
  image = "img/author.png"
  headline = "å› ä¸€å¿µæœ‰æ— æ•°ç”Ÿç­è€Œä»¿ä½›æ— å¤„å¯é€ƒï¼Œç”±æ˜¯ï¼Œå¿ƒæ— æ”¾é€¸ï¼Œä¸å¤±ä¼—å–„ã€‚"
  # bio = "ğŸŒˆ INTPï¼ŒğŸ§˜â€â™‚ï¸ Buddhist, ğŸ¬ Producer"
  links = [
     { email = "mailto:me@hhzz.top" },
  #   { link = "https://link-to-some-website.com/" },
  #   { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
  #   { apple = "https://www.apple.com" },
  #   { blogger = "https://username.blogspot.com/" },
  #   { codepen = "https://codepen.io/username" },
  #   { dev = "https://dev.to/username" },
  #   { discord = "https://discord.gg/invitecode" },
  #   { dribbble = "https://dribbble.com/username" },
  #   { facebook = "https://facebook.com/username" },
  #   { flickr = "https://www.flickr.com/photos/username/" },
  #   { foursquare = "https://foursquare.com/username" },
  #   { github = "https://github.com/username" },
  #   { gitlab = "https://gitlab.com/username" },
  #   { google = "https://www.google.com/" },
  #   { hashnode = "https://username.hashnode.dev" },
  #   { instagram = "https://instagram.com/username" },
  #   { keybase = "https://keybase.io/username" },
  #   { kickstarter = "https://www.kickstarter.com/profile/username" },
  #   { lastfm = "https://lastfm.com/user/username" },
  #   { linkedin = "https://linkedin.com/in/username" },
  #   { mastodon = "https://mastodon.instance/@username" },
  #   { medium = "https://medium.com/username" },
  #   { microsoft = "https://www.microsoft.com/" },
  #   { orcid = "https://orcid.org/userid" },
  #   { patreon = "https://www.patreon.com/username" },
  #   { pinterest = "https://pinterest.com/username" },
  #   { reddit = "https://reddit.com/user/username" },
  #   { researchgate = "https://www.researchgate.net/profile/username" },
  #   { slack = "https://workspace.url/team/userid" },
  #   { snapchat = "https://snapchat.com/add/username" },
  #   { soundcloud = "https://soundcloud.com/username" },
  #   { stack-overflow = "https://stackoverflow.com/users/userid/username" },
  #   { steam = "https://steamcommunity.com/profiles/userid" },
     { telegram = "https://t.me/justgoidea" },
  #   { tiktok = "https://tiktok.com/@username" },
  #   { tumblr = "https://username.tumblr.com" },
  #   { twitch = "https://twitch.tv/username" },
     { twitter = "https://twitter.com/lgtwet" },
  #   { whatsapp = "https://wa.me/phone-number" },
     { youtube = "https://youtube.com/@justgoidea" }
   ]
